name: DTT's Blog
short-name: dtt4725.github.io
description: DTT's technology blog
url: 
domain: http://dtt4725.github.io/
permalink: /blog/:year/:month/:day/:title/
disqus_shortname: dtt
markdown: redcarpet
pygments: true
port: 4444

# Author information
owner:
  name: Tingting Dong
  avatar: dtt.jpg
  bio: "QA，抠脚女汉子，热爱一切美好事物的2货处女座..."  
  email: dtt4725gmail.com 
  linkedin: "profile/view?id=52350907"

# Analytics and webmaster tools stuff goes here
google_analytics: UA-2635445-1
google_verify: I-NDFBl5t1P9fqHmRNZhwu8OOHmwW4HADPiOr_r16cE   
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Blog
    url: /blog
  - title: Contact Me
    url: /contact


timezone:    China/Beijing
future:      true